// <auto-generated />
using System;
using System.Collections.Generic;
using Consensus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consensus.Data.Migrations
{
    [DbContext(typeof(ConsensusDbContext))]
    partial class ConsensusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consensus.Core.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Dictionary<string, object>>("Data")
                        .HasColumnType("jsonb");

                    b.Property<long>("Difficulty")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MerkleRoot")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Nonce")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ProposerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProposerId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("ProposerId");

                    b.HasIndex("ProposerId1");

                    b.HasIndex("SimulationRunId1");

                    b.HasIndex("SimulationRunId", "BlockNumber");

                    b.HasIndex("SimulationRunId", "ProposerId", "CreatedAt");

                    b.ToTable("Blocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Block_BlockNumber", "\"BlockNumber\" >= 0");
                        });
                });

            modelBuilder.Entity("Consensus.Core.Entities.ConsensusRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("AgreedValue")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsensusThreshold")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaderId1")
                        .HasColumnType("uuid");

                    b.Property<int>("NegativeVotes")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipatingNodes")
                        .HasColumnType("integer");

                    b.Property<int>("PositiveVotes")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("ProposedValue")
                        .HasColumnType("jsonb");

                    b.Property<long>("RoundNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan?>("TimeoutDuration")
                        .HasColumnType("interval");

                    b.Property<int>("VotesReceived")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.HasIndex("LeaderId1");

                    b.HasIndex("SimulationRunId1");

                    b.HasIndex("Status");

                    b.HasIndex("SimulationRunId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ConsensusRounds", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlockId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsensusRoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsensusRoundId1")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Dictionary<string, object>>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Info");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("BlockId1");

                    b.HasIndex("ConsensusRoundId");

                    b.HasIndex("ConsensusRoundId1");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex("Level");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId1");

                    b.HasIndex("SimulationRunId1");

                    b.HasIndex("SimulationRunId", "Timestamp");

                    b.ToTable("EventLogs", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.NetworkTopology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[,]>("AdjacencyMatrix")
                        .HasColumnType("integer[]");

                    b.Property<double>("AverageConnections")
                        .HasColumnType("double precision");

                    b.Property<long>("BandwidthLimitBps")
                        .HasColumnType("bigint");

                    b.Property<Dictionary<string, object>>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxLatencyMs")
                        .HasColumnType("integer");

                    b.Property<double>("MessageLossProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("MinLatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<double>("PartitionProbability")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId1")
                        .HasColumnType("uuid");

                    b.Property<string>("TopologyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("SimulationRunId1");

                    b.HasIndex("TopologyType");

                    b.ToTable("NetworkTopologies", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ComputationalPower")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConnectionInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConsensusAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsByzantine")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NetworkLatency")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReputationScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StakeAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SimulationRunId", "Status");

                    b.HasIndex("SimulationRunId", "ConsensusAlgorithm", "Status");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.SimulationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ByzantineNodeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConsensusAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("Results")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TargetBlockCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsensusAlgorithm");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("SimulationRuns", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlockId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Dictionary<string, object>>("Data")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<long>("GasLimit")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GasPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("GasUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("InputData")
                        .HasColumnType("bytea");

                    b.Property<long>("Nonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Signature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<int?>("TransactionIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("BlockId1");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("SimulationRunId1");

                    b.HasIndex("SimulationRunId", "Status");

                    b.HasIndex("SimulationRunId", "BlockId", "Status");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Transaction_Fee", "\"Fee\" >= 0");
                        });
                });

            modelBuilder.Entity("Consensus.Core.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CastedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ConsensusRoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsensusRoundId1")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("Data")
                        .HasColumnType("jsonb");

                    b.Property<int>("NetworkDelayMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId1")
                        .HasColumnType("uuid");

                    b.Property<long>("Nonce")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Signature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CastedAt");

                    b.HasIndex("ConsensusRoundId1");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId1");

                    b.HasIndex("ConsensusRoundId", "NodeId")
                        .IsUnique();

                    b.HasIndex("ConsensusRoundId", "VoteType", "CastedAt");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("Consensus.Core.Entities.Block", b =>
                {
                    b.HasOne("Consensus.Core.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.Node", "Proposer")
                        .WithMany()
                        .HasForeignKey("ProposerId1");

                    b.HasOne("Consensus.Core.Entities.SimulationRun", null)
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany("Blocks")
                        .HasForeignKey("SimulationRunId1");

                    b.Navigation("Proposer");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.ConsensusRound", b =>
                {
                    b.HasOne("Consensus.Core.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.Node", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId1");

                    b.HasOne("Consensus.Core.Entities.SimulationRun", null)
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany("ConsensusRounds")
                        .HasForeignKey("SimulationRunId1");

                    b.Navigation("Leader");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.EventLog", b =>
                {
                    b.HasOne("Consensus.Core.Entities.Block", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId1");

                    b.HasOne("Consensus.Core.Entities.ConsensusRound", null)
                        .WithMany()
                        .HasForeignKey("ConsensusRoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.ConsensusRound", "ConsensusRound")
                        .WithMany()
                        .HasForeignKey("ConsensusRoundId1");

                    b.HasOne("Consensus.Core.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId1");

                    b.HasOne("Consensus.Core.Entities.SimulationRun", null)
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId1");

                    b.Navigation("Block");

                    b.Navigation("ConsensusRound");

                    b.Navigation("Node");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.NetworkTopology", b =>
                {
                    b.HasOne("Consensus.Core.Entities.SimulationRun", null)
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany("NetworkTopologies")
                        .HasForeignKey("SimulationRunId1");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.Node", b =>
                {
                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany("Nodes")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.Transaction", b =>
                {
                    b.HasOne("Consensus.Core.Entities.Block", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Consensus.Core.Entities.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("BlockId1");

                    b.HasOne("Consensus.Core.Entities.SimulationRun", null)
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.SimulationRun", "SimulationRun")
                        .WithMany("Transactions")
                        .HasForeignKey("SimulationRunId1");

                    b.Navigation("Block");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Consensus.Core.Entities.Vote", b =>
                {
                    b.HasOne("Consensus.Core.Entities.ConsensusRound", null)
                        .WithMany()
                        .HasForeignKey("ConsensusRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.ConsensusRound", "ConsensusRound")
                        .WithMany("Votes")
                        .HasForeignKey("ConsensusRoundId1");

                    b.HasOne("Consensus.Core.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consensus.Core.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId1");

                    b.Navigation("ConsensusRound");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Consensus.Core.Entities.Block", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Consensus.Core.Entities.ConsensusRound", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Consensus.Core.Entities.SimulationRun", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("ConsensusRounds");

                    b.Navigation("NetworkTopologies");

                    b.Navigation("Nodes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
